
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtacvndvovdhhjxlfhce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YWN2bmR2b3ZkaGhqeGxmaGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjc0MzIsImV4cCI6MjA1ODgwMzQzMn0.tGN9qV2cmCqpRCjS5cB9aP_SXDt1-3c4UkqK-NrbR3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
